services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=db
    restart: unless-stopped


  migrate:
    image: migrate/migrate
    container_name: migrations
    command: -path=/migrations -database postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE} up
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    restart: on-failure


  app:
    build:
     context: .
     dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    ports:
      - 8000:8080
    restart: unless-stopped
    env_file:
      - ./.env